export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',

    CHECK_EMAIL_REQUEST: 'USERS_EMAIL_CHECK_REQUEST',
    CHECK_EMAIL_SUCCESS: 'USERS_EMAIL_CHECK_SUCCESS',
    CHECK_EMAIL_FAILURE: 'USERS_EMAIL_CHECK_FAILURE',

    OTP_EMAIL_REQUEST: 'OTP_EMAIL_SENT_REQUEST',
    OTP_EMAIL_SUCCESS: 'OTP_EMAIL_SENT_SUCCESS',
    OTP_EMAIL_ALERT_DISMISS: 'OTP_EMAIL_ALERT_DISMISS',
    OTP_EMAIL_FAILURE: 'OTP_EMAIL_SENT_FAILURE',
};